movie_proj/movie_app/urls.py
from . import views
from django.urls import path
from .views import ListFeedBack, DetailFeedBack

urlpatterns = [
    path('', views.show_all_movie),
    path('movie/<slug:slug_movie>', views.show_one_movie, name = 'movie-detail'),
    path('directors/', views.show_directors),
    path('directors/<int:id_dir>', views.one_dir, name = 'one_dir'),
    path('actors/', views.show_actors),
    path('actors/<int:id_dir>', views.info_actor, name='one_actor'),
    path('actors/list', ListFeedBack.as_view()),
    path('detail/<int:pk>', DetailFeedBack.as_view()),
]

movie_proj/movie_proj/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Наша админка'
admin.site.index_title = 'Администрация'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

movie_proj/movie_app/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator

class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    director_email = models.EmailField()

    def get_url(self):
        return reverse('one_dir', args = [self.id])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class DressingRoom(models.Model):
    floor = models.IntegerField()
    number = models.IntegerField()

    def __str__(self):
        return f'{self.floor} {self.number}'

class Actor(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDERS = [
        (MALE, 'Мужчина'),
        (FEMALE, 'Женщина'),
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dressing = models.OneToOneField(DressingRoom, on_delete=models.SET_NULL, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDERS, default=MALE)

    def get_url(self):
        return reverse('one_actor', args = [self.id])

    def __str__(self):
        if self.gender == self.MALE:
            return f'Актер {self.first_name} {self.last_name}'
        else:
            return f'Актриса {self.first_name} {self.last_name}'

class Movie(models.Model):
    EURO = 'EUR'
    USD = 'USD'
    RUB = 'RUB'
    CURRENCY_CHOICES = [
        (EURO, 'Euro'),
        (USD, 'Dollars'),
        (RUB, 'Rubles'),
    ]
    # Создание полей
    name = models.CharField(max_length=40)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    year = models.IntegerField(null=True, blank=True)
    budget = models.IntegerField(default=10000000)
    currency = models.CharField(max_length=3, choices = CURRENCY_CHOICES, default= RUB)
    slug = models.SlugField(default='', null = False)
    director = models.ForeignKey(Director, on_delete=models.PROTECT, null=True)
    director_email = models.EmailField(default='sugar_daddy@gmail.com')
    actors = models.ManyToManyField(Actor)


    def get_url(self):
        return reverse('movie-detail', args=[self.slug])

    def __str__(self):
        return f'{self.name} - {self.rating}%'

movie_proj/movie_app/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import F, Sum, Max, Min, Count, Avg, Value
from .models import Movie, Director, Actor
from django.views.generic import ListView, DetailView


# Create your views here.

def show_all_movie(request):
    #movies = Movie.objects.order_by('name')
    movies = Movie.objects.annotate(
        true_bool = Value(True),
        false_bool = Value(False),
        str_field = Value('hello'),
        int_field = Value(123),
        new_budget = F('budget')+100,
        ffff=F('budget') * F('year'),
    )

    agg = movies.aggregate(Avg('budget'), Max('rating'), Min('rating'))
    return render(request, 'movie_app/all_movies.html', {
        'movies': movies,
        'agg': agg
    })

def show_one_movie(request, slug_movie:str):
    movie = get_object_or_404(Movie, slug=slug_movie)
    return render(request, 'movie_app/one_movie.html', {
        'movie': movie
    })

def show_directors(request):
    name_directors = Director.objects.all()
    return render(request, 'movie_app/all_directors.html', {
        'name_directors' : name_directors
    })

def one_dir(request, id_dir):
    dir = get_object_or_404(Director, id=id_dir)
    return render(request, 'movie_app/director_info.html', {
        'dir': dir
    })

def show_actors(request):
    actors = Actor.objects.all()
    return render(request, 'movie_app/actors.html', {
        'actors' : actors
    })

def info_actor(request, id_dir):
    actor = get_object_or_404(Actor, id=id_dir)
    return render(request, 'movie_app/info_actor.html', {
        'actor': actor
    })

class ListFeedBack(ListView):
    template_name = 'movie_app/all_actors.html'
    model = Actor

class DetailFeedBack(DetailView):
    template_name = 'movie_app/detail_actor.html'
    model = Actor

movie_proj/movie_app/templates/movie_app/actors.html
{% extends 'movie_app/base.html' %}

{% block title %} Актеры {% endblock %}

{% block content %}
    <h2> Список всех актеров</h2>
    <ul>
        {% for actor in actors %}
            <li><a href="{{ actor.get_url }}">
                {% if actor.gender is actor.MALE %}
                    Актер {{ actor.first_name }} {{ actor.last_name }}
                {% else %}
                    Актриса {{ actor.first_name }} {{ actor.last_name }}
                {% endif %}
            </a></li>
        {% endfor %}
    </ul>
{% endblock %}

movie_proj/movie_app/templates/movie_app/all_actors.html
{% extends 'movie_app/base.html' %}


{% block title %}
    Список всех актеров
{% endblock %}

{% block content %}
<form>
      <table>
        <h2>Список всех актеров </h2>
        <thead>
        <tr>
        <th>Фамилия</th>        <th>Имя</th>        <th>Отзыв</th>        <th>Рейтинг</th>
        </tr>
        </thead>
            <tbody>
            {% for feedback in object_list %}
            <tr>
<td>{{feedback.first_name}}</td>  <td>{{feedback.last_name}}</td>  <td>{{feedback.dressing}}</td> <td>{{feedback.gender}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
{% endblock %}

movie_proj/movie_app/templates/movie_app/all_directors.html
{% extends 'movie_app/base.html' %}

{% block title %} Режиссеры {% endblock %}

{% block content %}
    <h2> Список всех режиссеров</h2>
    <ul>
        {% for director in name_directors %}
            <li><a href="{{ director.get_url }}"> {{ director.first_name }} {{ director.last_name }} </a></li>
        {% endfor %}
    </ul>
{% endblock %}

movie_proj/movie_app/templates/movie_app/all_movies.html
{% extends 'movie_app/base.html' %}

{% block title %} {% endblock %}

{% block content %}
    <h2>Список всех фильмов</h2>
    <ul>
        {% for movie in movies %}
            <li><a href="{{ movie.get_url }}">{{ movie.name }}</a>,
                рейтинг 'Кинопоиск' - {{ movie.rating }}
                год - {{ movie.year }}
                бюджет - {{ movie.budget }}
            </li>
        {% endfor %}
    </ul>

    <h3>Средний бюджет - {{ agg.budget__avg }}</h3>
    <h3>Минимальный рейтинг - {{ agg.rating__min }}</h3>
    <h3>Максимальный рейтинг - {{ agg.rating__max }}</h3>
{% endblock %}

movie_proj/movie_app/templates/movie_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

{% block content %}

{% endblock %}
</body>
</html>

movie_proj/movie_app/templates/movie_app/detail_actor.html
{% extends 'movie_app/base.html' %}

{% block title %}
    Один актер
{% endblock %}

{% block content %}
    <h2>Информация об актере</h2>
    <h3>Имя - {{ actor.first_name }}</h3>
    <h3>Фамилия - {{ actor.last_name }}</h3>
    <h3>Рейтинг - {{ actor.gender }}</h3>
{% endblock %}

movie_proj/movie_app/templates/movie_app/director_info.html
{% extends 'movie_app/base.html' %}

{% block title %} Режиссеры {% endblock %}

{% block content %}
    <h3> Режиссер </h3>
    <h2> Имя - {{ dir.first_name }}</h2>
    <h2> Фамилия - {{ dir.last_name }}</h2>
    <h2> Почта - {{ dir.director_email }}</h2>
    <hr>
    <h3> Список фильмов </h3>
    <ul>
        {% for movie in dir.movie_set.all %}
            <li>{{ movie }}</li>
        {% endfor %}
    </ul>
{% endblock %}

movie_proj/movie_app/templates/movie_app/info_actor.html
{% extends 'movie_app/base.html' %}

{% block title %} Актеры {% endblock %}

{% block content %}
    <h3> Актер </h3>
    <h2> Имя - {{ actor.first_name }}</h2>
    <h2> Фамилия - {{ actor.last_name }}</h2>
    <h2> Пол - {{ actor.gender }}</h2>
{% endblock %}

movie_proj/movie_app/templates/movie_app/one_movie.html
{% extends 'movie_app/base.html' %}

{% block title %} Информация о фильме - {{ movie.name }} {% endblock %}

{% block content %}
    <h2> Информация о фильме - {{ movie.name }}</h2>
    <h3> Рейтинг {{ movie.rating }}</h3>
    <h3> Бюджет {{ movie.budget }}</h3>
    <h3> Год выхода {{ movie.year }}</h3>
    <hr>
    <h3> Информация о режиссере </h3>
    <h3> Имя {{ movie.director.first_name }}</h3>
    <h3> Фамилия {{ movie.director.last_name }}</h3>
    <h3> Почта {{ movie.director.director_email }}</h3>
    <hr>
    <h3> Список актеров </h3>
    <ul>
        {% for actor in movie.actors.all %}
            <li>{{ actor }}</li>
        {% endfor %}
    </ul>
{% endblock %}